### ISSUE TITLE
Why parallelize?

### ISSUE THREAD

**Issue by player-03** [onehundredfeet/hmecs#2]
> ```haxe
> @:parallel(FULL) // | @:p(FULL) - Valid values FULL | DOUBLE | HALF | # - Will create threads to call this function in parallel according to the number specifed in the parameters.  Will collect all threads before continuing.
> @:bucket(5) // | @:b(5) Specifies the parallel bucketing size valid values MAX | # - Max will take total / threads
> @:fork(SPRITE_UPDATE) // - Named synchronization - Will split off this update in another thread and continue processing other updates, can be combined with @:parallel
> @:u inline function updateSpritePosition(spr:Sprite, pos:Position) {
>   spr.x = pos.x;
>   spr.y = pos.y;
> }
> 
> // PARALLEL API NOT IMPLEMENTED YET
> @:join(SPRITE_UPDATE) // - Will wait until the corresponding fork is completed before running this function
> @:u inline function afterSpritePositionsUpdated() {
>   // rendering, etc
> }
> ```

In my opinion, threads are best used for large, self-contained tasks. Things like loading a large file, or solving an equation. Something that doesn't involve updating memory that's also in use by the rest of the program. An ECS is pretty much the opposite of that. Everything is broken up into miniature tasks, and these tasks constantly access and modify memory.

Just look at `updateSpritePosition`: in the span of two lines it reads two values and writes two more. What if something else also wants to update those values, and thanks to `@:fork`, they happen at the same time?

Plus, I'm concerned it'll be too many fork/join operations. Once in a while is fine, but every single frame? Potentially _multiple_ per frame? I wouldn't trust that to perform well across devices and targets. Maybe on good computers in pure C++, but in HashLink, message-passing seems to incur a more significant penalty. Disclaimer: I was testing thread performance in general, not this specifically. But it did seem that there was a fixed delay at the start of each job, regardless of whether I used `Deque` or `Thread.readMessage()`.

**Comment by onehundredfeet** [comment]
That's a great question. I designed the API before looking at HashLink's thread overhead. The use case is primarily for large pools of high computations like ray tracing, collision or physics. 

I hope to find a thread model that has the low overhead I'm used to in C++.  There's some haxe libraries for concurrency but I wonder if they are built on the questionable fundamentals. 

The examples below are just toy examples to demonstrate the api.  

Based on your comments, I will definitely do some profiling before implementing the final API.

The fork/join was a thought experiment of trying to define an API that relates the thread containment to the core program flow. Since the systems are already implicitly defining program flow, it seemed natural to embed the parallelism within it. Keeping them more obvious and a little more defined felt like these constraints would ultimately allow you to build more sophisticated systems without running into a lot of the regular synchronization issues. Ie you are effectively claiming ownership of the entities / components you are operating on so it's best to weave it into the system declaration you avoid conflicts.  

The joins also provide a simple way of doing dependency chains where multiple systems can join on the same identifier, which may be a non-standard way to use join tbh.

Great question. Thanks for the insight.

**Comment by player-03** [comment]
I'm not sure what else to say besides, good luck with all that. I've personally had enough threads for a long while.

**Comment by onehundredfeet** [comment]
I've been looking into the threading issues and I've just found a bunch of discussion about how bad it is.  Do you have any hard data anywhere?

**Comment by player-03** [comment]
No, sorry. You can check out my [two side-by-side HTML5 implementations](https://player03.com/openfl/threads-guide/#demo-virtualthreads) (top is single-threaded, bottom is multi-threaded, hover to see how long a job took). However, those come with a _lot_ of caveats, including that they were designed to measure the performance of large jobs, not message-passing. And certainly not passing several messages per frame.

**Comment by onehundredfeet** [comment]
I think we've hashed this through.
